test_web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('whois.urls',namespace="whois")),
]

whois/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from whois import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^result/$',views.show_result,name='show_result'),
]

whois/models.py
from django.db import models

# Create your models here.

whois/views.py
from django.shortcuts import render
from django.template import Context, loader
from django.http import HttpResponse,HttpResponseRedirect
from django.db import connection
from collections import namedtuple
from django.shortcuts import render_to_response 
from django.template import RequestContext
from django.contrib import auth
import urllib.request
import re
from bs4 import BeautifulSoup

def index(request,error=0):
	tmpl=loader.get_template("index.html")
	
	extension=['com','co','edu','gov','info','net','org','ac','mil','tv','ws']
	if error==1:
		context=RequestContext(request, {'extension':extension,'error':error})
	else:
		context=RequestContext(request, {'extension':extension,})

	return HttpResponse(tmpl.render(context))

def show_result(request):
	tmpl=loader.get_template("result.html")
	domain_name=request.POST.get('domain_name',"")
	extension=""
	found=0
	for i in range(0,len(domain_name)):
		if found==1:
			extension+=str(domain_name[i])
		if domain_name[i]=='.':
			found=1
	print(extension)
	extension_list=['com','co','edu','gov','info','net','org','ac','mil','tv','ws']
	found=0
	for ii in extension_list:
		if extension==ii:
			found=1
	if found==0:
		return index(request,1)
	url = "http://domainreg.btcl.com.bd/domain/show/%s.bd"%(domain_name,)
	request1 = urllib.request.Request(url)
	response = urllib.request.urlopen(request1)
	data=response.read().decode('utf-8')
	print("done loading page")

	#print(data)
	print("After ...")

	soup=BeautifulSoup(data,"html.parser")
	domain_info=soup.findAll('dd')
	info=[]

	for item in domain_info:
	    print(item.contents[0])
	    info.append(item.contents[0])
	print(info)    
	
	
	if len(info)==0:
		available='true'
		context=RequestContext(request,{'info':info,'available':available,'extension':extension_list})
		return HttpResponse(tmpl.render(context))

	context=RequestContext(request,{'info':info,'extension':extension_list})
	return HttpResponse(tmpl.render(context))
# Create your views here.

whois/templates/index.html
<html>
<head>   {% load staticfiles %} {% load bootstrap3 %}
 

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
  <script src="{% static "jquery.min.js" %}"></script>
  <script src="{% static "bootstrap.min.js" %}"></script>

  <meta charset="utf-8">

   <link rel="stylesheet" href="{% static "jquery-ui.css" %}">
  <script src="{% static "jquery-ui.js" %}"></script>
  <script src="{% static "jquery-1.10.2.js" %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
      		<a class="navbar-brand" href="{%url 'whois:index'%}"><font color='GreenYellow'>Whois</font></a>
    	</div>
	</div>
</nav>

<div class='row'>
	<div class='col-md-2'></div>

	<div class='col-md-8'>
				<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- bd whois -->
		<ins class="adsbygoogle"
		     style="display:block"
		     data-ad-client="ca-pub-4885494030443975"
		     data-ad-slot="2059239294"
		     data-ad-format="auto"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
	<div class='col-md-2'></div>
</div>

<div class="page-header text-center" >


  <h3>Search for your desired domain</h3>    
  {%if error%}  
  <div class="alert alert-danger">
   Enter valid domain!
	</div>
{%endif%}
</div>
<div class='row'>
	<div class='col-md-2'></div>
	<div class='col-md-8'>
		<div class='well'>
			<div class='row'>
				<div class='col-md-2'></div>
				<div class='col-md-6'>
					<form role='form' method='post' action="{%url 'whois:show_result'%}">
						<div class='form-group'>
						 {% csrf_token %}
						<input type='text' placeholder="enter domain name without www and .bd" name='domain_name' class='form-control' id='search_domain'>
						</div>
					
				</div>
				<div class='col-md-4'><input type='submit' value='search' class='btn btn-success'> </div>
			</div>
			</form>
		</div>
	</div>
	<div class='col-md-2'></div>
</div>
</body>

<script >

 $(document).ready(function() {
 	jQuery.noConflict(); 
 	var tags=[];
 	$( "#search_domain" ).autocomplete({
        source: function( request, response ) {
                var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( request.term ), "i" );
                response( $.grep( tags, function(item){
                    return matcher.test( item );
                }) );
            }
      });

 	$("#search_domain").keyup(function(){
 		var e=this.value;
 		var i=0;
 		tags=[];
 		var x='';
 		for(i=0;i<e.length;i++)
 		{
 			if (e[i]=='.')
 			{
 				{%for ii in extension%}
 					tags.push(x+"."+"{{ii}}");
 				{%endfor%}
 				break;
 			}
 			x+=e[i];
 		}
 	});

 });

</script>

</html>

whois/templates/result.html
<html>
<head>   {% load staticfiles %} {% load bootstrap3 %}
 

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
  <script src="{% static "jquery.min.js" %}"></script>
  <script src="{% static "bootstrap.min.js" %}"></script>

  <meta charset="utf-8">

   <link rel="stylesheet" href="{% static "jquery-ui.css" %}">
  <script src="{% static "jquery-ui.js" %}"></script>
  <script src="{% static "jquery-1.10.2.js" %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
      		<a class="navbar-brand" href="{%url 'whois:index'%}"><font color='GreenYellow'>Whois</font></a>
    	</div>
	</div>
</nav>
<div class="page-header text-center" >
  <h3>Search for your desired domain</h3>    
  {%if error%}  
  <div class="alert alert-danger">
   Enter valid domain!
	</div>
{%endif%}
</div>
<div class='row'>
	<div class='col-md-2'></div>
	<div class='col-md-8'>
		<div class='well'>
			<div class='row'>
				<div class='col-md-2'></div>
				<div class='col-md-6'>
					<form role='form' method='post' action="{%url 'whois:show_result'%}">
						<div class='form-group'>
						 {% csrf_token %}
						<input type='text' placeholder="enter domain name without www and .bd" name='domain_name' class='form-control' id='search_domain'>
						</div>
					
				</div>
				<div class='col-md-4'><input type='submit' value='search' class='btn btn-success'> </div>
			</div>
			</form>
		</div>
	</div>
	<div class='col-md-2'></div>
</div>

{%if available%}
  <div class="alert alert-success">
   Domain is available!!
	</div>

{%else%}
  <div class="alert alert-danger">
   Domain is not available!!
	</div>

	<table  class='table table-hover'>
	<tr>
		<td>Domain name</td>
		<td>{{info.0}}</td>
	</tr>
	<tr>
		<td>Registrant Name</td>
		<td>{{info.1}}</td>
	</tr>
	<tr>
		<td>Contact Email</td>
		<td>{{info.2}}</td>
	</tr>
	<tr>
		<td>Due Date</td>
		<td>{{info.3}}</td>
	</tr>
</table>
{%endif%}



</body>

<script >

 $(document).ready(function() {
 	jQuery.noConflict(); 
 	var tags=[];
 	$( "#search_domain" ).autocomplete({
        source: function( request, response ) {
                var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( request.term ), "i" );
                response( $.grep( tags, function(item){
                    return matcher.test( item );
                }) );
            }
      });

 	$("#search_domain").keyup(function(){
 		var e=this.value;
 		var i=0;
 		tags=[];
 		var x='';
 		for(i=0;i<e.length;i++)
 		{
 			if (e[i]=='.')
 			{
 				{%for ii in extension%}
 					tags.push(x+"."+"{{ii}}");
 				{%endfor%}
 				break;
 			}
 			x+=e[i];
 		}
 	});

 });

</script>

</html>